Repository BrokkAi/brokk, pull requests merged in 2025-08, with the labels that each got.

#590 Disable GPG Signing if Enabled in Config
  app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java
  app/src/test/java/io/github/jbellis/brokk/GitProjectStateRestorerTest.java
  app/src/test/java/io/github/jbellis/brokk/git/GitRepoMergeConflictTest.java
  app/src/test/java/io/github/jbellis/brokk/git/GitRepoRemoteMergeTest.java
  gradle/libs.versions.toml
Labels: bug

#647 Disable `ScrollFrameThrottlerTest` on Windows
  app/src/test/java/io/github/jbellis/brokk/difftool/scroll/ScrollFrameThrottlerTest.java
Labels: bug

#651 [0.12] Joern Java Analyzer Skeleton Supports Inheritance
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/PruneTypesPass.scala
  joern-analyzers/src/test/resources/testcode-java/XExtendsY.java
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzerTest.scala
Labels: enhancement, code analysis

#591 Git-Based Ranking Algorithms
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java
  app/src/main/java/io/github/jbellis/brokk/ContextManager.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/ASTTraversalUtils.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/context/Context.java
  app/src/main/java/io/github/jbellis/brokk/git/GitDistance.java
  app/src/main/java/io/github/jbellis/brokk/gui/mop/webview/MOPWebViewHost.java
  app/src/main/java/io/github/jbellis/brokk/tools/SearchTools.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistanceTestSuite.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/JavaTreeSitterAnalyzerGitInverseCooccurenceTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/JavaTreeSitterAnalyzerGitPMITest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/JavaTreeSitterAnalyzerGitPageRankTest.java
  app/src/test/resources/testcode-git-rank-java/NotificationService.java
  app/src/test/resources/testcode-git-rank-java/User.java
  app/src/test/resources/testcode-git-rank-java/UserRepository.java
  app/src/test/resources/testcode-git-rank-java/UserService.java
  app/src/test/resources/testcode-git-rank-java/ValidationService.java
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/DisabledAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/JavaAnalyzerTest.scala
Labels: enhancement, code analysis

#648 Rearrange Workspace, Combine Git and Project Files
  .brokk/project.properties
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
  app/src/main/java/io/github/jbellis/brokk/gui/FilterBox.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitCommitBrowserPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitIssuesTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitLogTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitPullRequestsTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/IssueHeaderCellRenderer.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/PullRequestHeaderCellRenderer.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/VerticalLabel.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/WrapLayout.java
  app/src/main/resources/icons/GOOGLE_MATERIAL_LICENSE.txt
  app/src/main/resources/icons/README.md
  app/src/main/resources/icons/dark/add_diamond.png
  app/src/main/resources/icons/dark/adjust.png
  app/src/main/resources/icons/dark/commit.png
  app/src/main/resources/icons/dark/content_copy.png
  app/src/main/resources/icons/dark/difference.png
  app/src/main/resources/icons/dark/download.png
  app/src/main/resources/icons/dark/folder_code.png
  app/src/main/resources/icons/dark/open_in_browser.png
  app/src/main/resources/icons/dark/person.png
  app/src/main/resources/icons/dark/publish.png
  app/src/main/resources/icons/dark/pull_request.png
  app/src/main/resources/icons/dark/refresh.png
  app/src/main/resources/icons/light/add_diamond.png
  app/src/main/resources/icons/light/adjust.png
  app/src/main/resources/icons/light/commit.png
  app/src/main/resources/icons/light/content_copy.png
  app/src/main/resources/icons/light/difference.png
  app/src/main/resources/icons/light/download.png
  app/src/main/resources/icons/light/folder_code.png
  app/src/main/resources/icons/light/open_in_browser.png
  app/src/main/resources/icons/light/person.png
  app/src/main/resources/icons/light/publish.png
  app/src/main/resources/icons/light/pull_request.png
  app/src/main/resources/icons/light/refresh.png
Labels: ui

#667 Badges in Workspace Panel Share Row with Desc
  app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
Labels: ui

#521 Improved code completion with safeguards, performance, and user experience enhancements
  .brokk/project.properties
  app/src/main/java/io/github/jbellis/brokk/Completions.java
  app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
Labels: ui

#721 Fix: Deduplicate Files before Reading
  app/src/main/java/io/github/jbellis/brokk/agents/ContextAgent.java
Labels: bug

#725 Fix Duplicate Actions in File Preview
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
Labels: bug, ui

#728 Using Friendlier Diff Representation
  app/src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitUiUtil.java
Labels: ui

#739 File Preview Captures Exact Token
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
  app/src/test/resources/testcode-java/A.java
Labels: ui

#708 Compositional Analyzer Capability Checks
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/CallGraphProvider.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/CapabilityProvider.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/DisabledAnalyzer.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/HasDelayedCapabilities.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/IncrementalUpdateProvider.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/SkeletonProvider.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/SourceCodeProvider.java
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/UsagesProvider.java
  app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java
  app/src/main/java/io/github/jbellis/brokk/AnalyzerWrapper.java
  app/src/main/java/io/github/jbellis/brokk/ContextManager.java
  app/src/main/java/io/github/jbellis/brokk/agents/ContextAgent.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/JavaAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/JdtAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/SqlAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/cli/BrokkCli.java
  app/src/main/java/io/github/jbellis/brokk/context/Context.java
  app/src/main/java/io/github/jbellis/brokk/context/ContextFragment.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/CallGraphDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/MultiFileSelectionDialog.java
  app/src/main/java/io/github/jbellis/brokk/tools/SearchTools.java
  app/src/main/java/io/github/jbellis/brokk/tools/WorkspaceTools.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/GoAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavascriptAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/PhpAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/SearchBehaviorComparisonTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/SqlAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzerRustTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/testutil/TestContextManager.java
  app/src/test/java/io/github/jbellis/brokk/tools/SkeletonPrinter.java
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/CppAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/DisabledAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/CppAnalyzerTest.scala
Labels: enhancement, code analysis

#762 Minimize Side Tabs on Click
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Labels: ui

#780 Check Analyser Capabilities Before Offering Capture Option
  app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
Labels: bug, ui, code analysis

#755 Completions: Heuristic-Based Retrieval over Expensive "Get All" Approach
  app/src/main/java/io/github/jbellis/brokk/Completions.java
  app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
Labels: ui

#791 `LspAnalyzer`: Enable Field Support on `getUses`
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/UsagesProvider.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspLanguageClient.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/PreviewTextPanel.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
Labels: bug, code analysis

#792 macOS: Themed Title Bar
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Labels: ui

#806 GitDistance: Most Important Files
  app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java
  app/src/main/java/io/github/jbellis/brokk/git/GitDistance.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistanceMostImportantTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistancePMITest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/GitDistanceTestSuite.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/ranking/TestProjectWithRepo.java
Labels: code analysis
