Repository BrokkAi/brokk, pull requests merged in 2025-09, with the labels that each got.

#804 Handle invalid file paths from LLM interactions
  app/src/main/java/io/github/jbellis/brokk/EditBlock.java
  app/src/main/java/io/github/jbellis/brokk/agents/CodeAgent.java
  app/src/main/java/io/github/jbellis/brokk/prompts/CodePrompts.java
  app/src/main/java/io/github/jbellis/brokk/prompts/EditBlockConflictsParser.java
  app/src/main/java/io/github/jbellis/brokk/prompts/EditBlockParser.java
  app/src/main/java/io/github/jbellis/brokk/tools/WorkspaceTools.java
  app/src/test/java/io/github/jbellis/brokk/EditBlockConflictsParseAllBlocksTest.java
  app/src/test/java/io/github/jbellis/brokk/EditBlockConflictsTest.java
  app/src/test/java/io/github/jbellis/brokk/EditBlockParseAllBlocksTest.java
  app/src/test/java/io/github/jbellis/brokk/EditBlockTest.java
Labels: bug

#839 Separated Completion Task from Wrangling `searchDefinitions` to Dedicated `autocompleteDefinitions`
  analyzer-api/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/Completions.java
  app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/MultiAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerSearchTest.java
  app/src/test/java/io/github/jbellis/brokk/testutil/MockAnalyzer.java
Labels: bug, code analysis

#837 History Fetches Latest Items on Dropdown + Dynamic Truncation
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
Labels: bug, ui

#847 JDT: More Reliable Source Code Handling
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzerHelper.java
Labels: bug, code analysis

#854 Enforce Buttons are Present in Commit Tab
  app/src/main/java/io/github/jbellis/brokk/gui/GitCommitTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/ResponsiveButtonPanel.java
Labels: ui

#856 GitPanelTab Components Now Split into Main (Chrome) Tab
  app/src/main/java/io/github/jbellis/brokk/GitHubAuth.java
  app/src/main/java/io/github/jbellis/brokk/context/ContextFragment.java
  app/src/main/java/io/github/jbellis/brokk/difftool/ui/BrokkDiffPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/AutoScalingHtmlPane.java
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
  app/src/main/java/io/github/jbellis/brokk/gui/GitPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/MenuBar.java
  app/src/main/java/io/github/jbellis/brokk/gui/ProjectFilesPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/ProjectTree.java
  app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/CreatePullRequestDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/OpenProjectDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SessionsDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitCommitBrowserPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitCommitTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitHistoryTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitIssuesTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitLogTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitPullRequestsTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitWorktreeTab.java
  app/src/main/java/io/github/jbellis/brokk/gui/menu/ContextMenuBuilder.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/GitUiUtil.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/Icons.java
  app/src/main/resources/icons/dark/flowchart.svg
  app/src/main/resources/icons/dark/flowsheet.svg
  app/src/main/resources/icons/light/flowchart.svg
  app/src/main/resources/icons/light/flowsheet.svg
  app/src/test/java/io/github/jbellis/brokk/gui/GitUiUtilTest.java
Labels: ui, refactoring

#870 Ignored-by-default Test Code Checkbox in Usage Dialog
  app/src/main/java/io/github/jbellis/brokk/ContextManager.java
  app/src/main/java/io/github/jbellis/brokk/context/ContextFragment.java
  app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SymbolSelectionDialog.java
Labels: code analysis

#891 Double Click Title Bar Maximize/Normal Functionality
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Labels: bug, ui

#893 Remove `joern-analyzers` and use `CppTreeSitterAnalyzer`
  .scalafmt.conf
  app/build.gradle.kts
  app/src/main/development.md
  app/src/main/java/io/github/jbellis/brokk/analyzer/Language.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/linting/JdtAnalyzerLintingTest.java
  gradle/libs.versions.toml
  joern-analyzers/build.gradle.kts
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/CppAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/JoernAnalyzer.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/CpgBuilder.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/FileChange.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/IncrementalUtils.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/CBuilder.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/languages/package.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/base/FileContentClearing.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/cpp/PointerTypesPass.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/HashFilesPass.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/PruneTypesPass.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/builder/passes/incremental/RemovedFilePass.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/implicits/AstNodeExt.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/implicits/CpgExt.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/implicits/PathExt.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/implicits/StringExt.scala
  joern-analyzers/src/main/scala/io/github/jbellis/brokk/analyzer/implicits/X2CpgConfigExt.scala
  joern-analyzers/src/main/scala/io/joern/c2cpg/passes/AstCreationPass.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/base/ContainsEdgePass.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/base/FileCreationPass.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/base/NamespaceCreator.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/callgraph/DynamicCallLinker.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/callgraph/StaticCallLinker.scala
  joern-analyzers/src/main/scala/io/joern/x2cpg/passes/frontend/TypeNodePass.scala
  joern-analyzers/src/test/resources/testcode-cpp/geometry.cpp
  joern-analyzers/src/test/resources/testcode-cpp/geometry.h
  joern-analyzers/src/test/resources/testcode-cpp/main.cpp
  joern-analyzers/src/test/resources/testcode-cpp/nested.cpp
  joern-analyzers/src/test/resources/testcode-cpp/pytorch.cpp
  joern-analyzers/src/test/resources/testcode-java/A.java
  joern-analyzers/src/test/resources/testcode-java/AnonymousUsage.java
  joern-analyzers/src/test/resources/testcode-java/B.java
  joern-analyzers/src/test/resources/testcode-java/BaseClass.java
  joern-analyzers/src/test/resources/testcode-java/C.java
  joern-analyzers/src/test/resources/testcode-java/CamelClass.java
  joern-analyzers/src/test/resources/testcode-java/CyclicMethods.java
  joern-analyzers/src/test/resources/testcode-java/D.java
  joern-analyzers/src/test/resources/testcode-java/E.java
  joern-analyzers/src/test/resources/testcode-java/F.java
  joern-analyzers/src/test/resources/testcode-java/Interface.java
  joern-analyzers/src/test/resources/testcode-java/MethodReturner.java
  joern-analyzers/src/test/resources/testcode-java/Packaged.java
  joern-analyzers/src/test/resources/testcode-java/UseE.java
  joern-analyzers/src/test/resources/testcode-java/UsePackaged.java
  joern-analyzers/src/test/resources/testcode-java/XExtendsY.java
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/CppAnalyzerTest.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/CpgTestFixture.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/FileChangeTest.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/IncrementalBuildTestFixture.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/CallGraphTest.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/IncrementalBuildTest.scala
  joern-analyzers/src/test/scala/io/github/jbellis/brokk/analyzer/builder/cpp/SimpleBuildTest.scala
  settings.gradle.kts
Labels: code analysis, refactoring

#904 Fix JavaAnalyzer Logic on Update
  app/src/main/java/io/github/jbellis/brokk/analyzer/JavaAnalyzer.java
Labels: bug, code analysis

#909 Added Cleanup after Sandbox Tests
  app/src/test/java/io/github/jbellis/brokk/util/EnvironmentTest.java
Labels: bug

#922 Side Panel Maximizes to Remembered Size
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Labels: ui

#960 Enable Class Summaries + Fix Auto-Complete
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/MultiFileSelectionDialog.java
Labels: bug

#779 MCP Client Support
  .brokk/project.properties
  app/build.gradle.kts
  app/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingChatModel.java
  app/src/main/java/dev/langchain4j/model/openai/internal/Json.java
  app/src/main/java/dev/langchain4j/model/openai/internal/RequestExecutor.java
  app/src/main/java/io/github/jbellis/brokk/IProject.java
  app/src/main/java/io/github/jbellis/brokk/Llm.java
  app/src/main/java/io/github/jbellis/brokk/MainProject.java
  app/src/main/java/io/github/jbellis/brokk/agents/ArchitectAgent.java
  app/src/main/java/io/github/jbellis/brokk/gui/components/McpToolTable.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ArchitectOptionsDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsGlobalPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsProjectPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/Icons.java
  app/src/main/java/io/github/jbellis/brokk/mcp/HttpMcpServer.java
  app/src/main/java/io/github/jbellis/brokk/mcp/McpConfig.java
  app/src/main/java/io/github/jbellis/brokk/mcp/McpServer.java
  app/src/main/java/io/github/jbellis/brokk/mcp/McpUtils.java
  app/src/main/java/io/github/jbellis/brokk/mcp/StdioMcpServer.java
  app/src/main/java/io/github/jbellis/brokk/prompts/McpPrompts.java
  app/src/main/java/io/github/jbellis/brokk/util/Environment.java
  app/src/main/resources/icons/dark/help.svg
  app/src/main/resources/icons/dark/visibility.svg
  app/src/main/resources/icons/dark/visibility_off.svg
  app/src/main/resources/icons/light/help.svg
  app/src/main/resources/icons/light/visibility.svg
  app/src/main/resources/icons/light/visibility_off.svg
  app/src/test/java/io/github/jbellis/brokk/testutil/TestProject.java
  gradle/libs.versions.toml
Labels: enhancement, ui

#932 Feat/tab navigation & configure keyboard shortcuts
  app/src/main/java/io/github/jbellis/brokk/MainProject.java
  app/src/main/java/io/github/jbellis/brokk/SettingsChangeListener.java
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsGlobalPanel.java
  cli.bat
Labels: enhancement

#993 Replaced Instances Where `isCpg` was Used with `AnalyzerWrapper/Language` Capability API
  app/src/main/java/io/github/jbellis/brokk/AnalyzerWrapper.java
  app/src/main/java/io/github/jbellis/brokk/agents/MergeOneFile.java
  app/src/main/java/io/github/jbellis/brokk/agents/SearchAgent.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/JavaLanguage.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/Language.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/Languages.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/PythonLanguage.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/RustLanguage.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ArchitectOptionsDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/MultiFileSelectionDialog.java
Labels: ui, code analysis, performance

#1029 Fix Usages of Nested Class Constructors
  app/src/main/java/io/github/jbellis/brokk/analyzer/JdtAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspAnalyzer.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
Labels: bug, code analysis

#1044 Normalize `$` Class Separators as `.`
  app/src/main/java/io/github/jbellis/brokk/AnalyzerUtil.java
  app/src/main/java/io/github/jbellis/brokk/FuzzyMatcher.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzer.java
  app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerSearchTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/PythonAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/testutil/MockAnalyzer.java
Labels: bug, code analysis

#1057 Add "Configure" Button when MCP Servers are Empty
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ArchitectOptionsDialog.java
Labels: ui

#1091 Fix Missing Java Enum Constants & Method Modifiers
  app/src/main/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/resources/treesitter/java.scm
  app/src/test/java/io/github/jbellis/brokk/analyzer/JavaTreeSitterAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/JdtAnalyzerTest.java
  app/src/test/resources/testcode-java/A.java
  app/src/test/resources/testcode-java/EnumClass.java
Labels: bug, code analysis

#1167 En/add enhance prompt button
  app/src/main/java/io/github/jbellis/brokk/Service.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/Icons.java
  app/src/main/resources/icons/dark/wand.svg
  app/src/main/resources/icons/light/wand.svg
Labels: enhancement, ui

#1168 997 bug dependencies are racy
  app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesPanel.java
Labels: bug

#1176 Increase Linting Settle Delay + Improved Path Normalisation in Diagnostics
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspLanguageClient.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/lsp/LspServer.java
Labels: bug, code analysis

#1181 Feature: improve context sent to architect with tasks
  app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
Labels: enhancement

#1180 TreeSitter Updates Use `mtime` Instead of Hashes
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
Labels: code analysis, performance

#1179 Revert Back to Serial Analyzer Creation
  app/src/main/java/io/github/jbellis/brokk/analyzer/Language.java
Labels: code analysis, performance

#1217 no search on first task
  app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
  app/src/test/java/io/github/jbellis/brokk/gui/terminal/TaskListPanelTest.java
Labels: bug
