Repository BrokkAi/brokk, pull requests merged in 2025-10, with the labels that each got.

#1231 Merge TreeSitterAnalyzer Maps
  app/src/main/java/io/github/jbellis/brokk/analyzer/CodeUnitProperties.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/CppTreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/FileProperties.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/PhpAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TreeSitterAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/TypescriptAnalyzer.java
  app/src/main/java/io/github/jbellis/brokk/analyzer/cpp/NamespaceProcessor.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/CSharpAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/GoAnalyzerTest.java
  app/src/test/java/io/github/jbellis/brokk/analyzer/PythonAnalyzerTest.java
Labels: code analysis, refactoring

#1236 Bug/sync branch visuals between project drawer, gitlog tab, and branch selector in instructions panel
  app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/git/GitLogTab.java
Labels: bug, ui

#1240 Fix/session save tasks
  app/src/main/java/io/github/jbellis/brokk/SessionManager.java
  app/src/main/java/io/github/jbellis/brokk/TaskListData.java
  app/src/main/java/io/github/jbellis/brokk/TaskListEntryDto.java
  app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
  app/src/test/java/io/github/jbellis/brokk/SessionManagerTaskListIoTest.java
  app/src/test/java/io/github/jbellis/brokk/SessionManagerTaskListLifecycleTest.java
Labels: bug

#1257 Allows combining multiple tasks, updates UI, merges texts, and manages done states
  app/src/main/java/io/github/jbellis/brokk/gui/terminal/TaskListPanel.java
Labels: ui

#1282 Configurable auto-compression, improved history UI, and compression settings panel
  app/src/main/java/io/github/jbellis/brokk/ContextManager.java
  app/src/main/java/io/github/jbellis/brokk/MainProject.java
  app/src/main/java/io/github/jbellis/brokk/gui/HistoryOutputPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsGlobalPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/Icons.java
  app/src/main/resources/icons/dark/compress.svg
  app/src/main/resources/icons/light/compress.svg
Labels: enhancement, ui, refactoring

#1280 Improved Git metadata handling, UI reliability, and observability with logging and retries
  app/src/main/java/io/github/jbellis/brokk/AnalyzerWrapper.java
  app/src/main/java/io/github/jbellis/brokk/ContextManager.java
  app/src/main/java/io/github/jbellis/brokk/MainProject.java
  app/src/main/java/io/github/jbellis/brokk/ProjectWatchService.java
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
Labels: bug, ui

#1290 Default `autocompleteDefinitions` Overapproximates for Possible Acronyms
  app/src/main/java/io/github/jbellis/brokk/analyzer/IAnalyzer.java
  app/src/test/java/io/github/jbellis/brokk/CompletionsTest.java
Labels: code analysis

#1313 Move workspace into instructions
  app/src/main/java/io/github/jbellis/brokk/gui/Chrome.java
  app/src/main/java/io/github/jbellis/brokk/gui/InstructionsPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/WorkspaceItemsChipPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/WorkspacePanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesDrawerPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dependencies/DependenciesPanel.java
  app/src/main/java/io/github/jbellis/brokk/gui/dialogs/ImportDependencyDialog.java
  app/src/main/java/io/github/jbellis/brokk/gui/util/ContextMenuUtils.java
Labels: ui
